"""Write the branch-closure record from the result files, not from memory.

Two development branches are being closed. A closure that gets summarised by
hand drifts -- numbers get rounded toward the story, a caveat gets dropped,
and six weeks later the record says something the runs do not. This reads the
JSON the runs actually wrote and states the verdict against criteria fixed
before the numbers were read.

  policy-form   whether ANY threshold over the existing P1, local and
                reliability scores carries a full-taxonomy-safe auto-keep tail
                of usable size. Closed if v5 returns no solution.
  validity-gate whether the undecidable candidates can be detected well enough
                to remove upstream. Closed if the gate removes under half of
                them, or drops any real boundary.

A closure is not a claim that the idea is wrong. It is a claim that THESE
signals do not support it, so the next attempt needs a new observable rather
than another threshold. The record says which, because the difference decides
what gets built next.

Usage:
    python -m src.boundary.c3_branch_closure \
        --policy_v4 /workspace/tr1/results/hal/c3/policy_v4.json \
        --policy_v5 /workspace/tr1/results/hal/c3/policy_v5.json \
        --validity_gate /workspace/tr1/results/hal/c3/validity_gate.json \
        --out docs/branch_closure_2026_08_06.md
"""
from __future__ import annotations

import argparse
import json
import os


def load(p):
    if not p or not os.path.exists(p):
        return None
    with open(p, encoding="utf-8") as f:
        return json.load(f)


def dig(d, *keys, default=None):
    for k in keys:
        if not isinstance(d, dict) or k not in d:
            return default
        d = d[k]
    return d


def role_block(res, role):
    """The development metrics a role actually selected, or None if it found
    nothing. The distinction matters more than any number inside."""
    if not res:
        return None
    r = res.get(role) if isinstance(res, dict) else None
    if isinstance(r, dict) and r.get("selected"):
        return r
    for k in ("roles", "results"):
        v = res.get(k)
        if isinstance(v, dict) and role in v:
            return v[role]
        if isinstance(v, list):
            for e in v:
                if isinstance(e, dict) and e.get("role") == role:
                    return e
    return r


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--policy_v4")
    ap.add_argument("--policy_v5", required=True)
    ap.add_argument("--validity_gate", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    v4, v5, vg = load(a.policy_v4), load(a.policy_v5), load(a.validity_gate)
    if v5 is None:
        raise SystemExit(f"--policy_v5 {a.policy_v5} not found. The closure is "
                         f"written FROM the runs; without the feasibility "
                         f"result there is nothing to record.")
    if vg is None:
        raise SystemExit(f"--validity_gate {a.validity_gate} not found")

    L = []
    w = L.append
    w("# Branch closure, written from the result files\n")
    w("Generated by `c3_branch_closure.py` from the JSON the runs wrote. "
      "Criteria were fixed before the numbers were read.\n")

    # ---------------------------------------------------------- policy form
    w("## Policy form\n")
    w("**Question.** Does any threshold over the existing P1, local and "
      "reliability scores carry an auto-keep tail that is safe under the FULL "
      "taxonomy and large enough to matter (at least 20 events)?\n")
    closed_policy = True
    for role in ("primary_transportability_frontier",
                 "secondary_one_error_buffered"):
        b = role_block(v5, role)
        sel = dig(b, "selected") if b else None
        if sel:
            closed_policy = False
            prec = dig(b, "development", "full_taxonomy_auto_keep_precision",
                       default=dig(b, "development", "auto_keep_precision"))
            n = dig(b, "development", "n_all_auto_keep",
                    default=dig(b, "development", "n_auto_keep"))
            w(f"- `{role}`: **a solution exists** -- {n} auto-keeps at "
              f"full-taxonomy precision {prec}. The branch does NOT close; "
              f"report this point and its nested behaviour before anything "
              f"else.\n")
        else:
            w(f"- `{role}`: no policy in the grid satisfies the constraints.\n")
    if closed_policy:
        w("\n**Closed.** Not because the constraints are too strict -- they are "
          "the deployment requirement -- but because the tail these scores "
          "produce is contaminated by candidates the verifier was never "
          "trained to reject. Widening the grid, lowering the size floor or "
          "relaxing the precision would each produce a number, and none would "
          "produce a safe system.\n")
        if v4:
            w("\nThe closest thing that did pass, under the earlier "
              "clean-binary constraint (v4), is on record as a keep-only "
              "high-abstention baseline and NOT a candidate for held-out "
              "evaluation: its clean-binary precision reads high because the "
              "events it wrongly keeps are absent from that denominator.\n")

    # -------------------------------------------------------- validity gate
    w("\n## Validity gate\n")
    w("**Question.** Can the candidates with no decidable boundary be detected "
      "well enough to remove upstream?\n")
    closed_gate = True
    for tag, r in vg.items():
        if not isinstance(r, dict) or "n_removed" not in r:
            continue
        n_rm = r["n_removed"]
        prec = r.get("precision")
        sharp = r.get("n_sharp_dropped", 0)
        w(f"\n- **{tag}**: AUROC {r.get('auroc')}, removed {n_rm} at precision "
          f"{prec}, real boundaries dropped **{sharp}**, per fold "
          f"{r.get('per_fold_n')}.\n")
        if sharp == 0 and isinstance(prec, (int, float)) and prec >= 0.95 \
                and n_rm >= 20:
            closed_gate = False
            w("  This one PASSES the fixed criteria.\n")
        else:
            reasons = []
            if sharp:
                reasons.append(f"{sharp} real boundaries discarded")
            if not isinstance(prec, (int, float)) or prec < 0.95:
                reasons.append(f"removal precision {prec} below 0.95")
            if n_rm < 20:
                reasons.append(f"only {n_rm} removed")
            w(f"  Fails: {'; '.join(reasons)}.\n")
    if closed_gate:
        w("\n**Closed.** The decomposition of REVIEW into nuisance, "
          "recoverable and genuinely hard remains true as a description and "
          "unavailable as an action. The nuisance candidates keep going to a "
          "human, and any review rate quoted after subtracting them is an "
          "oracle bound, not a reachable figure.\n")

    # --------------------------------------------------------------- what next
    w("\n## What a closure does and does not mean\n")
    w("Neither branch is closed because the idea is wrong. Both are closed "
      "because THESE signals -- global Qwen side vectors, local hand-crop "
      "vectors, detection reliability -- do not support them at a deployable "
      "operating point. Reopening either requires a new observable, not "
      "another threshold over the same scores.\n")
    w("\nThe consequence for what gets built next is direct: no further "
      "threshold search, no further fusion of the existing scores, and no "
      "held-out evaluation until a single primary policy exists that was "
      "selected on the deployed metric.\n")

    os.makedirs(os.path.dirname(os.path.abspath(a.out)) or ".", exist_ok=True)
    with open(a.out, "w", encoding="utf-8") as f:
        f.write("".join(L))
    print("".join(L))
    print(f"\nwrote {a.out}")
    print(f"policy-form closed: {closed_policy}   "
          f"validity-gate closed: {closed_gate}")


if __name__ == "__main__":
    main()
